### ISSUE TITLE
Make MiddlewareFactory replaceable

### ISSUE THREAD

**Issue by arku31** [mezzio/mezzio#52]
As this class is extendable and I do extend it, I would be happy to have this property as `protected`. Otherwise, everything that happens in parents constructor, stays in parent constructor, which leads to constructor duplication in the child class.
https://github.com/mezzio/mezzio/blob/7d71a4887fb0a4dc99e39dd7c4a79fea2bb36170/src/MiddlewareFactory.php#L56

**Comment by boesing** [comment]
Actually, this factory might become `final` in one of the next versions while adding an `Interface` to it.

Would you be open for a Pull-Request where you create an `MiddlewareFactoryInterface` which implements those public methods which can be found in the current implementation?
We could then change the consumer of this factory (`Application#__construct`) to use the new `MiddlewareFactoryInterface` while also registering that interface to the `PSR-11` container.

In the end, you can provide your own `MiddlewareFactory` instead of extending the current one.

So when finished, you end up decorating the current `MiddlewareFactory` and you can provide your very own logic without depending on the concrete implementation of `mezzio/mezzio`.

----

This could be the solution for your project then:

```php
namespace Example;

use Mezzio\MiddlewareFactory;
use Mezzio\MiddlewareFactoryInterface;

final class ProjectSpecificMiddlewareFactoryDecorator implements MiddlewareFactoryInterface
{
     public function __construct(
       private readonly MiddlewareFactoryInterface $mezzioMiddlewareFactory
     )
     {
     }

     // implement methods and proxy to mezzio middleware factory when needed
}
```

**Comment by arku31** [comment]
Hi, using an interface approach is totally fine for me :)
